/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stopwatch;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author charith_ds
 */
public class MyStopwatch2 extends javax.swing.JFrame {

    /**
     * Creates new form MyStopwatch2
     */
    boolean start_stop_ButtonClick, lapButtonClick;
    static TimeCounter mainTimeCounter2;
    static TimeCounter lapTimeCounter2;
    
    public MyStopwatch2() {
        jFrameSettings();
        GridValue.activeFrames=false;
        lapButton.setEnabled(false);

    }

    public MyStopwatch2(boolean startButtonClick, boolean lapButtonEnable) {
        jFrameSettings();
        GridValue.activeFrames = true;
        lapButton.setEnabled(false);
        if (startButtonClick) {
            start_stop_ButtonClick = startButtonClick;
            start_stop_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/pause_15px.png")));
            if(lapButtonEnable){
                lapButtonClick = lapButtonEnable;
                lapButton.setEnabled(true);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        maximiseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lapValue = new javax.swing.JLabel();
        lapButton = new javax.swing.JButton();
        start_stop_Button = new javax.swing.JButton();
        lapNumberDisplay = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(44, 44, 45));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/macos_close_15px.png"))); // NOI18N
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        maximiseButton.setBackground(new java.awt.Color(47, 47, 48));
        maximiseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/shrink_15px.png"))); // NOI18N
        maximiseButton.setAlignmentY(0.0F);
        maximiseButton.setBorder(null);
        maximiseButton.setBorderPainted(false);
        maximiseButton.setContentAreaFilled(false);
        maximiseButton.setFocusPainted(false);
        maximiseButton.setRequestFocusEnabled(false);
        maximiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximiseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(maximiseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(maximiseButton))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(28, 29, 31));
        jPanel2.setForeground(new java.awt.Color(223, 223, 223));

        lapValue.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lapValue.setForeground(new java.awt.Color(223, 223, 223));
        lapValue.setText("00 : 00 : 00");
        lapValue.setAlignmentY(0.0F);

        lapButton.setBackground(new java.awt.Color(0, 0, 0));
        lapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/xbox_l_15px.png"))); // NOI18N
        lapButton.setAlignmentY(0.0F);
        lapButton.setBorder(null);
        lapButton.setBorderPainted(false);
        lapButton.setContentAreaFilled(false);
        lapButton.setFocusPainted(false);
        lapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapButtonActionPerformed(evt);
            }
        });

        start_stop_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/play_15px.png"))); // NOI18N
        start_stop_Button.setAlignmentY(0.0F);
        start_stop_Button.setBorder(null);
        start_stop_Button.setBorderPainted(false);
        start_stop_Button.setContentAreaFilled(false);
        start_stop_Button.setFocusPainted(false);
        start_stop_Button.setRequestFocusEnabled(false);
        start_stop_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_stop_ButtonActionPerformed(evt);
            }
        });

        lapNumberDisplay.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        lapNumberDisplay.setForeground(new java.awt.Color(223, 223, 223));
        lapNumberDisplay.setText("00");
        lapNumberDisplay.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lapValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(start_stop_Button)
                        .addGap(18, 18, 18)
                        .addComponent(lapButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(78, Short.MAX_VALUE)
                    .addComponent(lapNumberDisplay)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lapValue)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(start_stop_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(lapNumberDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/stopwatch_50px.png"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 54, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_stop_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_stop_ButtonActionPerformed
        lapButton.setEnabled(true);
        mainTimeCounter2.start();
        if (!start_stop_ButtonClick) {
            start_stop_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/pause_15px.png"))); //main timer has started
            if (lapButtonClick) {
                lapTimeCounter2.start();
            }
            start_stop_ButtonClick = true;
        } else {
            start_stop_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/play_15px.png"))); //main timer has stopped
            mainTimeCounter2.stop();
            lapTimeCounter2.stop();
            start_stop_ButtonClick = false;
            lapButton.setEnabled(false);
        }
    }//GEN-LAST:event_start_stop_ButtonActionPerformed

    private void maximiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximiseButtonActionPerformed

        MyStopwatch myStopwatch;
        
        if (GridValue.activeFrames || start_stop_ButtonClick) {
            myStopwatch = new MyStopwatch(start_stop_ButtonClick, true);
            
        } else {
            myStopwatch = new MyStopwatch();
        }
        
        MyStopwatch.mainTimeCounter = mainTimeCounter2;
        MyStopwatch.mainTimeCounter.timeCounterMethod(MyStopwatch.totalTime);

        MyStopwatch.lapTimeCounter = lapTimeCounter2;
        MyStopwatch.lapTimeCounter.timeCounterMethod(MyStopwatch.lapTime);
        

        myStopwatch.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_maximiseButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapButtonActionPerformed
        lapButtonClick = true;

        lapTimeCounter2.reset();
        lapTimeCounter2.start();

        GridValue.lapNumber++;

        GridValue.min_maxCalculation();

        if (GridValue.lapNumber != 1) {
            GridValue.gridDisplay(lapTimeCounter2.lapValues, mainTimeCounter2.lapValues, false);
        } else {
            GridValue.gridDisplay(mainTimeCounter2.lapValues, mainTimeCounter2.lapValues, false);
        }
    }//GEN-LAST:event_lapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyStopwatch2().setVisible(true);
            }
        });
    }

    void jFrameSettings() {

        //move jFrame after removing the title bar
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        
        initComponents();

        //set jframe at the left right corner
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width - this.getWidth() - 6, screenSize.height - this.getHeight() - 47);
        //this.setLocation(1425, 790);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lapButton;
    static javax.swing.JLabel lapNumberDisplay;
    static javax.swing.JLabel lapValue;
    private javax.swing.JButton maximiseButton;
    private javax.swing.JButton start_stop_Button;
    // End of variables declaration//GEN-END:variables
}
