/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stopwatch;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicScrollBarUI;
import static stopwatch.GridValue.gridStore;

/**
 *
 * @author charith_ds
 */
public class MyStopwatch extends javax.swing.JFrame {

    /**
     * Creates new form MyStopwatch
     */
    boolean startButtonClick = false;
    boolean lapButtonClick = false;
    boolean resetButtonClick = false;
    boolean dnButtonClick = false;
    int mpX, mpY;
    static TimeCounter mainTimeCounter;
    static TimeCounter lapTimeCounter;
    static GridValue displayGrid;

    public MyStopwatch() {
        
        jFrameSettings();
        GridValue.activeFrames=false;
        GridValue.lap_List = new ArrayList<>();
        lapButton.setEnabled(false);
        mainTimeCounter = new TimeCounter(totalTime);
        lapTimeCounter = new TimeCounter(lapTime);
    }
    
    public MyStopwatch(Boolean startButtonClick, Boolean lapButtonClick){
    
        jFrameSettings();
        
        lapDetails.setText(gridStore);
        lapDetails.setCaretPosition(0);
        gridStore="";
        GridValue.activeFrames = true;
        this.startButtonClick = startButtonClick;
    
        lapButton.setEnabled(false);
        if (startButtonClick) {
            this.startButtonClick = startButtonClick;
            startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/stop_light.png")));
            if(lapButtonClick){
                this.lapButtonClick = lapButtonClick;
                lapButton.setEnabled(true);
            }
            
        }
        
        GridValue.colorLines();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        lapTime = new javax.swing.JLabel();
        totalTime = new javax.swing.JLabel();
        lapButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        miniViewButton = new javax.swing.JButton();
        minimiseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        lapDetails = new javax.swing.JTextPane(GridValue.doc);
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(28, 29, 31));
        setForeground(java.awt.Color.darkGray);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 44, 45));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusable(false);

        startButton.setBackground(new java.awt.Color(44, 44, 45));
        startButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/start_light.png"))); // NOI18N
        startButton.setAlignmentY(0.0F);
        startButton.setBorder(null);
        startButton.setBorderPainted(false);
        startButton.setContentAreaFilled(false);
        startButton.setFocusPainted(false);
        startButton.setFocusable(false);
        startButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        lapTime.setFont(new java.awt.Font("Verdana", 0, 23)); // NOI18N
        lapTime.setForeground(new java.awt.Color(153, 153, 153));
        lapTime.setAlignmentY(0.0F);
        lapTime.setFocusable(false);

        totalTime.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        totalTime.setForeground(new java.awt.Color(223, 223, 223));
        totalTime.setText("00 : 00 : 00");
        totalTime.setAlignmentY(0.0F);

        lapButton.setBackground(new java.awt.Color(44, 44, 45));
        lapButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/lap_light.png"))); // NOI18N
        lapButton.setAlignmentY(0.0F);
        lapButton.setBorder(null);
        lapButton.setBorderPainted(false);
        lapButton.setContentAreaFilled(false);
        lapButton.setFocusPainted(false);
        lapButton.setFocusable(false);
        lapButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(44, 44, 45));
        resetButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/reset_light.png"))); // NOI18N
        resetButton.setAlignmentY(0.0F);
        resetButton.setBorder(null);
        resetButton.setBorderPainted(false);
        resetButton.setContentAreaFilled(false);
        resetButton.setFocusPainted(false);
        resetButton.setFocusable(false);
        resetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(47, 47, 48));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/macos_close_25px.png"))); // NOI18N
        jButton1.setToolTipText("Close");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(47, 47, 47));
        jButton2.setForeground(new java.awt.Color(47, 47, 47));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/180_degree_25px.png"))); // NOI18N
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/help_20px.png"))); // NOI18N
        jLabel4.setToolTipText("Help");
        jLabel4.setAlignmentY(0.0F);
        jLabel4.setFocusable(false);

        miniViewButton.setBackground(new java.awt.Color(47, 47, 48));
        miniViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/shrink_25px.png"))); // NOI18N
        miniViewButton.setToolTipText("Close");
        miniViewButton.setAlignmentY(0.0F);
        miniViewButton.setBorder(null);
        miniViewButton.setBorderPainted(false);
        miniViewButton.setContentAreaFilled(false);
        miniViewButton.setFocusPainted(false);
        miniViewButton.setFocusable(false);
        miniViewButton.setRequestFocusEnabled(false);
        miniViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniViewButtonActionPerformed(evt);
            }
        });

        minimiseButton.setBackground(new java.awt.Color(47, 47, 48));
        minimiseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/minimize_window_25px.png"))); // NOI18N
        minimiseButton.setToolTipText("Close");
        minimiseButton.setAlignmentY(0.0F);
        minimiseButton.setBorder(null);
        minimiseButton.setBorderPainted(false);
        minimiseButton.setContentAreaFilled(false);
        minimiseButton.setFocusPainted(false);
        minimiseButton.setFocusable(false);
        minimiseButton.setRequestFocusEnabled(false);
        minimiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimiseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lapTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(startButton)
                                .addGap(9, 9, 9)
                                .addComponent(lapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton))
                            .addComponent(totalTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miniViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {resetButton, startButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(miniViewButton)
                    .addComponent(minimiseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lapTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startButton)
                            .addComponent(resetButton)
                            .addComponent(lapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addComponent(jLabel4))
                .addGap(16, 16, 16))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lapButton, resetButton, startButton});

        lapButton.getAccessibleContext().setAccessibleName("lapButton");
        resetButton.getAccessibleContext().setAccessibleName("resetButton");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 186));

        jPanel2.setBackground(new java.awt.Color(28, 29, 31));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(41, 42, 42));
        jSeparator2.setAlignmentX(0.0F);
        jSeparator2.setAlignmentY(0.0F);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 420, 10));

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(28, 29, 31));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAlignmentX(0.0F);
        jScrollPane2.setAlignmentY(0.0F);
        jScrollPane2.setRequestFocusEnabled(false);

        lapDetails.setEditable(false);
        lapDetails.setBackground(new java.awt.Color(28, 29, 31));
        lapDetails.setBorder(null);
        lapDetails.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lapDetails.setForeground(new java.awt.Color(28, 29, 31));
        lapDetails.setAlignmentX(0.0F);
        lapDetails.setAlignmentY(0.0F);
        lapDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lapDetails.setFocusable(false);
        lapDetails.setRequestFocusEnabled(false);
        lapDetails.setSelectedTextColor(new java.awt.Color(28, 29, 31));
        jScrollPane2.setViewportView(lapDetails);

        jScrollPane2.getVerticalScrollBar().setBackground(new Color(28,29,31));

        jScrollPane2.getVerticalScrollBar().setUI(new BasicScrollBarUI(){
            protected void configureScrollBarColors(){
                this.thumbColor = new Color(197,198,198);
            }
        });

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 140));

        jLabel3.setForeground(new java.awt.Color(197, 198, 198));
        jLabel3.setText("Lap");
        jLabel3.setAlignmentY(0.0F);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, -1));

        jLabel2.setForeground(new java.awt.Color(197, 198, 198));
        jLabel2.setText("Overall time");
        jLabel2.setAlignmentY(0.0F);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 70, -1));

        jLabel1.setForeground(new java.awt.Color(197, 198, 198));
        jLabel1.setText("Lap Time");
        jLabel1.setAlignmentY(0.0F);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 60, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 450, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        resetButtonClick = true;
        startButtonClick = false;
        lapButtonClick = false;
        mainTimeCounter.reset();
        lapTimeCounter.reset();
        lapButton.setEnabled(false);
        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/start_light.png")));
        lapDetails.setText("");
        GridValue.lapNumber = 0;
        lapTime.setText("");
        GridValue.max_lapValue = 0;
        GridValue.max_lapNumber = 0;
        GridValue.lap_List.clear();
        GridValue.activeFrames=false;
    }//GEN-LAST:event_resetButtonActionPerformed

    private void lapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapButtonActionPerformed
        lapButtonClick = true;

        lapTimeCounter.reset();
        lapTimeCounter.start();

        GridValue.lapNumber++;

        GridValue.min_maxCalculation();

        //show lap summary
        if (GridValue.lapNumber != 1) {
            GridValue.gridDisplay(lapTimeCounter.lapValues, mainTimeCounter.lapValues, true);
        } else {
            GridValue.gridDisplay(mainTimeCounter.lapValues, mainTimeCounter.lapValues, true);
        }

    }//GEN-LAST:event_lapButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        lapButton.setEnabled(true);
        mainTimeCounter.start();
        if (!startButtonClick) {
            startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/stop_light.png"))); //main timer has started
            if (lapButtonClick) {
                lapTimeCounter.start();
            }
            startButtonClick = true;
        } else {
            startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/start_light.png"))); //main timer has stopped
            mainTimeCounter.stop();
            lapTimeCounter.stop();
            startButtonClick = false;
            lapButton.setEnabled(false);
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!dnButtonClick) {
            enableDayMode();

        } else {
            enableDarkMode();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void miniViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniViewButtonActionPerformed
 
        gridStore();
        
        MyStopwatch2 myStopwatch2;
        if (GridValue.activeFrames || startButtonClick) {
            
            myStopwatch2 = new MyStopwatch2(startButtonClick, true);
            
        } else {
            
            myStopwatch2 = new MyStopwatch2();
        }

        MyStopwatch2.mainTimeCounter2 = mainTimeCounter;
        MyStopwatch2.lapTimeCounter2 = lapTimeCounter;
        if (GridValue.lapNumber == 0) {
            MyStopwatch2.mainTimeCounter2.timeCounterMethod(MyStopwatch2.lapValue);
        } else {
            MyStopwatch2.lapTimeCounter2.timeCounterMethod(MyStopwatch2.lapValue);
        }
     
//        lapNumber_String = String.format("%02d", GridValue.lapNumber + 1);
//        MyStopwatch2.lapNumberDisplay.setText(lapNumber_String);

        myStopwatch2.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_miniViewButtonActionPerformed

    private void minimiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimiseButtonActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimiseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MyStopwatch().setVisible(true);
            }
        });
    }

    void enableDayMode() {

        //change to day mode
        jPanel1.setBackground(new Color(255, 255, 255));
        totalTime.setForeground(new Color(45, 45, 45));
        lapTime.setForeground(new Color(118, 118, 118));
        jLabel1.setForeground(new Color(45, 45, 45));
        jLabel2.setForeground(new Color(45, 45, 45));
        jLabel3.setForeground(new Color(45, 45, 45));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/help_20_dark_px.png")));
        jButton1.setBackground(new Color(255, 255, 255));
        jButton2.setBackground(new Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/180_degree_dark_25px.png")));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/macos_close_dark_25px.png")));
        miniViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/shrink_25_dark_px.png")));
        minimiseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/minimize_window_25_dark_px.png")));

        jPanel2.setBackground(new Color(227, 228, 230));
        dnButtonClick = true;

        //scroll bar color change
        jScrollPane2.getVerticalScrollBar().setBackground(new Color(227, 228, 230));

        jScrollPane2.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new Color(0, 0, 0);
            }
        });
    }

    void enableDarkMode() {

        //change to night mode
        jPanel1.setBackground(new Color(44, 44, 45));
        totalTime.setForeground(new Color(223, 223, 223));
        lapTime.setForeground(new Color(153, 153, 153));
        jLabel1.setForeground(new Color(197, 198, 198));
        jLabel2.setForeground(new Color(197, 198, 198));
        jLabel3.setForeground(new Color(197, 198, 198));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/help_20px.png")));
        jButton1.setBackground(new Color(47, 47, 48));
        jButton2.setBackground(new Color(47, 47, 48));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/180_degree_25px.png")));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/macos_close_25px.png")));
        miniViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/shrink_25px.png")));
        minimiseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sIcons/minimize_window_25px.png")));

        jPanel2.setBackground(new Color(28, 29, 31));
        dnButtonClick = false;

        //scroll bar color change
        jScrollPane2.getVerticalScrollBar().setBackground(new Color(28, 29, 31));

        jScrollPane2.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new Color(197, 198, 198);
            }
        });
    }
    
    void jFrameSettings(){

        //move jFrame after removing the title bar
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);

        initComponents();

        //enable day night mode
        LocalTime time = LocalTime.now();
        if (time.getHour() < LocalTime.of(18, 0).getHour() && time.getHour() > LocalTime.of(6, 0).getHour()) {
            enableDayMode();

        } else {
            enableDarkMode();
        }

        //change scroll bar size in textpane
        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(8, 0));

        
//        if (gridValue.lapNumber != 1) {
//            gridValue.gridDisplay(lapTimeCounter.lapValues, mainTimeCounter.lapValues);
//        } else {
//            gridValue.gridDisplay(mainTimeCounter.lapValues, mainTimeCounter.lapValues);
//        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lapButton;
    static javax.swing.JTextPane lapDetails;
    static javax.swing.JLabel lapTime;
    private javax.swing.JButton miniViewButton;
    private javax.swing.JButton minimiseButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton startButton;
    static javax.swing.JLabel totalTime;
    // End of variables declaration//GEN-END:variables
}
